name: ZithiumCaptcha
version: '${version}'
main: net.zithium.captcha.ZithiumCaptcha
api-version: '1.19'

commands:
  captcha:
    description: Main Command

permissions:
  captcha.admin:
    default: op
    children:
      - captcha.command.show